version: 2
jobs:
  build:
    working_directory: ~/java-demo-lib
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          key: java-demo-lib-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: java-demo-lib-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/java-demo-lib-1.0-SNAPSHOT.jar