version: 2.0
jobs:
  build_development:
    branches:
      only:
        - development
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "From development branch" 

  build_master:
    branches:
      only:
        - master
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "From master branch" 