version: 2.0
jobs:
  build:
    branches:
      only:
        - development
        - master 
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "From development branchXXX" 
