version: 2.1

parameters:
  params_file:
    type: string
    default: "params/parameters.list"

  workspace_path:
    type: string
    default: "/tmp/workspace"

workflows:
  version: 2

  btd:
    jobs:
      - initialize
      - build:
          requires:
            - initialize

jobs:
  initialize:
    working_directory: ~/java-demo-lib
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run: mkdir -p params
      - run: echo "PACKAGE_NAME=branch-1.0.1-SNAPSHOT" >> << pipeline.parameters.params_file >>
      - run: echo "BRANCH_TYPE=development" >> << pipeline.parameters.params_file >>
      - run: echo "PACKAGE_VERSION=1.0.1" >> << pipeline.parameters.params_file >>
      - persist_to_workspace:
          root: .
          paths:
            - params

  build:
    working_directory: ~/java-demo-lib
    shell: /bin/bash -eo pipefail
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: << pipeline.parameters.workspace_path >>

      - run: 
          name: "Setup custom environment variables"
          command: |
            while read p; do
              VAR_KEY=$(echo "$p" | cut -d "=" -f 1)
              VAR_VAL=$(echo "$p" | cut -d "=" -f 2)

              echo "export ${VAR_KEY}=${VAR_VAL}" >> $BASH_ENV
              echo "${VAR_KEY}=${VAR_VAL}"
            done < << pipeline.parameters.workspace_path >>/<< pipeline.parameters.params_file >>

      - checkout

      - restore_cache:
          key: java-demo-lib-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: java-demo-lib-{{ checksum "pom.xml" }}
      
      - run: mvn -Drevision=${PACKAGE_NAME} package 
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          # Env variables interpolation are not working here!!!
          path: target/${PACKAGE_NAME}.jar