version: 2

workflows:
  version: 2

  btd:
    jobs:
      - initialize
      - build:
          requires:
            - initialize

jobs:
  initialize:
    working_directory: ~/java-demo-lib
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run: mkdir -p params
      - run: echo "PACKAGE_NAME=branch-1.0.1-SNAPSHOT" >> params/parameters.list   
      - run: echo "BRANCH_TYPE=development" >> params/parameters.list
      - run: echo "PACKAGE_VERSION=1.0.1" >> params/parameters.list
      - persist_to_workspace:
          root: .
          paths:
            - params

  build:
    working_directory: ~/java-demo-lib
    shell: /bin/bash -eo pipefail
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run: 
          name: "Setup custom environment variables"
          command: |
            while read p; do
              echo 'export PACKAGE_NAME="branch-1.0.1-SNAPSHOT"' >> $BASH_ENV
              echo "$p"
            done </tmp/workspace/params/parameters.list

      - checkout

      - restore_cache:
          key: java-demo-lib-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: java-demo-lib-{{ checksum "pom.xml" }}
      
      - run: mvn -Drevision=${PACKAGE_NAME} package 
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/${PACKAGE_NAME}.jar