version: 2.0
jobs:
  build:
    #branches:
    #  only:
    #    - development
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "From development branchXXX" 

  build2:
    #branches:
    #  only:
    #    - master 
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "From master branchYYYY" 